// File Name         : params.h
// Description       : Changeable parameters to measure performance impact
// Table of Contents : input_reader.h parameters
// Revision History  :
//     Albert Ng      Nov 19 2012     Initial Revision

#ifndef CS316_CORE_PARAMS_H_
#define CS316_CORE_PARAMS_H_

#include <stdint.h>

// input_reader.h
uint64_t INPUT_READER_FIFO_LENGTH = 64;
uint64_t INPUT_READER_NUM_RAMS = 8;
uint64_t INPUT_READER_RAM_ADDR_ROW_WIDTH = 5;
uint64_t INPUT_READER_RAM_ADDR_COL_WIDTH = 5;
uint64_t INPUT_READER_RAM_ADDR_BANK_WIDTH = 3;
uint64_t INPUT_READER_RAM_ADDR_WIDTH = (INPUT_READER_RAM_ADDR_BANK_WIDTH + INPUT_READER_RAM_ADDR_ROW_WIDTH + INPUT_READER_RAM_ADDR_COL_WIDTH);
uint64_t INPUT_READER_SYSTEM_CLOCK_FREQ_MHZ = 200;
uint64_t INPUT_READER_MEMORY_CLOCK_FREQ_MHZ = 400;
uint64_t INPUT_READER_RAM_TRCD = 8;
uint64_t INPUT_READER_RAM_TCL = 7;
uint64_t INPUT_READER_RAM_TRP = 8;

// interval_table_ctrl.h
uint64_t INTERVAL_TABLE_CTRL_FIFO_LENGTH = 16;
uint64_t INTERVAL_TABLE_CTRL_NUM_RAMS = 8;
uint64_t INTERVAL_TABLE_CTRL_RAM_ADDR_ROW_WIDTH = 5;
uint64_t INTERVAL_TABLE_CTRL_RAM_ADDR_COL_WIDTH = 5;
uint64_t INTERVAL_TABLE_CTRL_RAM_ADDR_BANK_WIDTH = 3;
uint64_t INTERVAL_TABLE_CTRL_RAM_ADDR_WIDTH = (INTERVAL_TABLE_CTRL_RAM_ADDR_BANK_WIDTH + INTERVAL_TABLE_CTRL_RAM_ADDR_ROW_WIDTH + INTERVAL_TABLE_CTRL_RAM_ADDR_COL_WIDTH);
uint64_t INTERVAL_TABLE_CTRL_SYSTEM_CLOCK_FREQ_MHZ = 200;
uint64_t INTERVAL_TABLE_CTRL_MEMORY_CLOCK_FREQ_MHZ = 400;
uint64_t INTERVAL_TABLE_CTRL_RAM_TRCD = 8;
uint64_t INTERVAL_TABLE_CTRL_RAM_TCL = 7;
uint64_t INTERVAL_TABLE_CTRL_RAM_TRP = 8;

// position_table_ctrl.h
uint64_t POSITION_TABLE_CTRL_FIFO_LENGTH = 16;
uint64_t POSITION_TABLE_CTRL_NUM_RAMS = 8;
uint64_t POSITION_TABLE_CTRL_RAM_ADDR_ROW_WIDTH = 5;
uint64_t POSITION_TABLE_CTRL_RAM_ADDR_COL_WIDTH = 5;
uint64_t POSITION_TABLE_CTRL_RAM_ADDR_BANK_WIDTH = 3;
uint64_t POSITION_TABLE_CTRL_RAM_ADDR_WIDTH = (POSITION_TABLE_CTRL_RAM_ADDR_BANK_WIDTH + POSITION_TABLE_CTRL_RAM_ADDR_ROW_WIDTH + POSITION_TABLE_CTRL_RAM_ADDR_COL_WIDTH);
uint64_t POSITION_TABLE_CTRL_SYSTEM_CLOCK_FREQ_MHZ = 200;
uint64_t POSITION_TABLE_CTRL_MEMORY_CLOCK_FREQ_MHZ = 400;
uint64_t POSITION_TABLE_CTRL_RAM_TRCD = 8;
uint64_t POSITION_TABLE_CTRL_RAM_TCL = 7;
uint64_t POSITION_TABLE_CTRL_RAM_TRP = 8;


// ram_module.h
uint64_t RAM_MODULE_PORT_INPUT_FIFO_LENGTH = 64;
uint64_t RAM_MODULE_PORT_ROB_SIZE = 64;
uint64_t RAM_MODULE_INFLIGHT_FIFO_LENGTH = 64;

// stitcher.h
uint64_t STITCHER_OUTPUT_FIFO_LENGTH = 128;

#endif // CS316_CORE_PARAMS_H_
